# Configuration file for unit test
# ToDo: perhaps create mock in unit tests?

dns:
  log_level: info
  accounts:
    bam-test:
      provider: proteus
      cidr_file: config/cidr_test.json
      config:
        url: https://some.bluecat.server.com
        username: changeme
        password: changeme
        viewid: 123456
auth:
  token512:
    ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff:
      - POST
      - PUT
      - GET
      - DELETE
